### ISSUE TITLE
IfThen in C-API

### ISSUE THREAD

**Issue by IgnaceBleukx** [dimitri-justeau/choco-solver-capi#5]
Hi,

This issue is similar (and potentially related to) the [issue I raised in the main repository](https://github.com/chocoteam/choco-solver/issues/1072).
The methods for implying and reifing constraints seem to be missing from the C-API (and by extension the Python API too).

Are there any plans on adding these methods to the API?

Kind regards,
Ignace

**Comment by dimitri-justeau** [comment]
Hi Ignace,

Yes it is planned, especially if some people need it, it is just a matter of finding a bit of time to do it but it is definitely on the todolist :-)

Best regards,

Dimitri.

**Comment by dimitri-justeau** [comment]
Done https://github.com/chocoteam/pychoco/commit/04692f3371b1ccae5680fdeb168cb2f55db8e2e1
